export const UsersData=[
    {
        id:'1',
        name:"hussnain",
        position:"assoc",
        office:"lhr",
        salary:300
    },
    {
        id:'3',
        name:"hussnain2",
        position:"assoc",
        office:"lhr",
        salary:300
    },
    {
        id:'2',
        name:"hussnain3",
        position:"assoc",
        office:"lhr",
        salary:300
    }
];